import os

from dotenv import load_dotenv

load_dotenv()

GROQ_MODEL_TEMPERATURE = float(os.getenv('GROQ_MODEL_TEMPERATURE'))
GROQ_MODEL_NAME = os.getenv('GROQ_MODEL_NAME')
GROQ_API_KEY = os.getenv('GROQ_API_KEY')
EVOLUTION_API_URL = os.getenv('EVOLUTION_API_URL')
EVOLUTION_INSTANCE_NAME = os.getenv('EVOLUTION_INSTANCE_NAME')
EVOLUTION_AUTHENTICATION_API_KEY = os.getenv('AUTHENTICATION_API_KEY')
AI_CONTEXTUALIZE_PROMPT = os.getenv('AI_CONTEXTUALIZE_PROMPT')
AI_SYSTEM_PROMPT = os.getenv('AI_SYSTEM_PROMPT')
VECTOR_STORE_PATH = os.getenv('VECTOR_STORE_PATH')
RAG_FILES_DIR = os.getenv('RAG_FILES_DIR')
REDIS_URL = os.getenv('CACHE_REDIS_URI')
HUGGINGFACE_API_KEY = os.getenv('HUGGINGFACE_API_KEY')
BUFFER_KEY_SUFIX = os.getenv('BUFFER_KEY_SUFIX')
DEBOUNCE_TIME_SECONDS = os.getenv('DEBOUNCE_TIME_SECONDS')
BUFFER_TTL_SECONDS = os.getenv('BUFFER_TTL_SECONDS')
